export const DASHBOARD_LIST_MOVIE_REQUEST = "@dashboard/LIST_MOVIE_REQUEST";
export const DASHBOARD_LIST_MOVIE_SUCCESS = "@dashboard/LIST_MOVIE_SUCCESS";
export const DASHBOARD_LIST_MOVIE_FAILED = "@dashboard/LIST_MOVIE_FAILED";